### ISSUE TITLE
Error: container sharing network namespace with another container or host cannot be connected to any other network

### ISSUE THREAD

**Issue by BabyDino** [tjhorner/dragonify#1]
Hi, thank you for your work on the inter-app issues in Truenas. I am running one container which relies on another for networking, this causes dragonify to crash. 

```
> dragonify@1.0.0 start /app
> node dist/index.js
[25-02-04 09:28:59] info: Setting up network apps-internal
[25-02-04 09:28:59] info: Network already exists
/app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:382
      var msg = new Error(
                ^
Error: (HTTP code 400) unexpected - container sharing network namespace with another container or host cannot be connected to any other network 
    at /app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:382:17
    at getCause (/app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:417:7)
    at Modem.buildPayload (/app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:378:5)
    at IncomingMessage.<anonymous> (/app/node_modules/.pnpm/docker-modem@5.0.3/node_modules/docker-modem/lib/modem.js:346:16)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  reason: undefined,
  statusCode: 400,

{
    message: 'container sharing network namespace with another container or host cannot be connected to any other network'
  }
}
Node.js v20.18.1
 ELIFECYCLE  Command failed with exit code 1.
```

This is the stack:

```
services:
  gluetun:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
    ...
    image: qmcgaw/gluetun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - '8080:8080'
      - '6881:6881'
      - 6881:6881/udp
    restart: unless-stopped
  service-which-uses-gluetun:
    ...
    network_mode: service:gluetun
    restart: unless-stopped
```

I assume it is the `network_mode` which causes the crash.
